# PostgreSQL
postgres:
    image: postgres:9.6.0
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker

# Django app
bank:
    build: .
#    command: dev
    command: uwsgi
    ports:
      - 8012:8012
      - 8001:8001
    volumes:
      - ./bank:/usr/src/bank
    links:
      - postgres:postgres
    environment:
      - DEBUG=False
      - PORT=8012
      - POSTGRES_DB_NAME=bank
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
      - POSTGRES_PORT_5432_TCP_PORT=5432
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGPASSWORD=docker
      - SECRET_KEY=###DamjanDimitrioski###
      - WSGI_MODULE=bank.wsgi:application

web:
    build: nginx
    ports:
      - 80:80
    volumes:
      - ./bank/static:/static
    links:
      - bank:bank
